spring.application.name=blog 
spring.main.web-application-type=servlet
# Explicitly disable reactive security auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
 
# database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# optional: show SQL in logs for debugging
spring.jpa.show-sql=true

# //jwt
jwt.secret=${ACCESS_TOKEN_SECRET}
jwt.exp=${JWT_EXP}


#mx single file size
spring.servlet.multipart.max-file-size=20MB
#max siez for entire req
spring.servlet.multipart.max-request-size=25MB 
app.upload.dir=./uploads/